### ISSUE TITLE
Logging in & getting authentication token

### ISSUE THREAD

**Issue by amsharma9** [davellanedam/phalcon-micro-rest-api-skeleton#5]
Hi,

I am stuck at the first step. I have setup the environment with Wamp but I am unable to login. Pardon my lack of knowledge. I read most of the code in `app.php`, how to setup routes and acl etc. I then went deeper and read a few articles and tutorials about JWT on internet. I have never used it. How do I send my User/Password to the API. Earlier I had created a small REST API using node.js using a tutorial where we sent the credentials in a json object. I assume that will not work here.

I also understand that after authentication in `Response` object I will get the token which I have to use for all further calls. Second question, whose solution is most probably related to the first one, how will I send this token with each API call. I do see the config file `server.development.php` having space for the token and a key.

Amal

**Comment by davellanedam** [comment]
You should go to USAGE in the guide, you must use Postman or any other API client. I fact there's an included postman collection file in the skeleton for you with everything already setup, just follow the guide, it´s very easy. Hope it helps.
