### ISSUE TITLE
How to get the current user identity?

### ISSUE THREAD

**Issue by anbalaganr** [davellanedam/phalcon-micro-rest-api-skeleton#6]

**Comment by davellanedam** [comment]
Hey!, well that's easy, just call for the token inside your controller and decode it, like this:
`$token = $this->decodeToken($this->getToken());` afterwards you can call the different values of the token, like: `$token->username_username`, `$token->username_firstname`, `$token->username_lastname`, `$token->username_level`

**Comment by anbalaganr** [comment]
Thank you so much!!!

**Comment by davellanedam** [comment]
My pleasure bud, I hope this help you somehow.
