### ISSUE TITLE
Language files not being picked up?

### ISSUE THREAD

**Issue by ghost** [davellanedam/phalcon-micro-rest-api-skeleton#9]
I have created  file langs/en.json + es.json  as instructed in readme.md but they are not being picked up, and I can't see anything for internationalization in the code. Any guidance would be appreciated. Thank you

**Comment by davellanedam** [comment]
Hello, you need to add them in your frontend, not in the API, the API always returns constant like variables so you are able to handle those in the frontend. I hope this helps.
